<?php
return array(
  'main.page'=>array(
    'baseUrl'=>'/',
      'css'=>array('css/main.css')
  ),
  'ui'=>array(
      'baseUrl'=>'/js',
      'js'=>array('jquery-ui-1.8.16.custom.min.js'),
      'depends'=>array('calendar.locale','ui.css')
  ),
    'jquery.ui'=>array(
        'baseUrl'=>'/js',
        'js'=>array('jquery-ui-1.8.16.custom.min.js'),
        'depends'=>array('calendar.locale','ui.css')
    ),
    
  'calendar.locale'=>array(
      'baseUrl'=>'/js',
      'js'=>array('jquery.ui.datepicker-ru.js'),      
  ),
    
  'ui.css'=>array(
      'baseUrl'=>'/css/ui-lightness',
      'css'=>array('jquery-ui-1.8.16.custom.css')
  ),
  'jqGrid'=>array(
      'baseUrl'=>'/js/jqGrid/',
      'js'=>array('js/i18n/grid.locale-ru.js','js/jquery.jqGrid.min.js'),
      'css'=>array('css/ui.jqgrid.css')
  ),
    
  'jQuery'=>array(
      'baseUrl'=>'/js',
      'js'=>array('jquery-1.7.min.js')
  ),
    
  'mfupload'=>array(
      'baseUrl'=>'/js',
      'js'=>array('jquery.MetaData.js','jquery.MultiFile.js'),
      'depends'=>array('form')
  ),

  'form'=>array(
      'baseUrl'=>'/js',
      'js'=>array('jquery.form.js')
  ),
  'main.menu'=>array(
      'baseUrl'=>'/',
      'js'=>array('js/main.menu.js'),
      'css'=>array('css/main.menu.css')
  ),
  'checkbox'=>array(
      'baseUrl'=>'/',
      'js'=>array('js/checkbox/jquery.checkbox.js'),
      'css'=>array('css/checkbox/jquery.checkbox.css')
  ),
  'menu.right.click'=>array(
      'baseUrl'=>'/',
      'js'=>array('js/jquery.contextmenu.r2.js'),
      'css'=>array('css/contextMenu.css')
  ),  
  'jbar'=>array(
        'baseUrl'=>'/',
        'js'=>array('js/jbar/jquery.bar.js'),
        'css'=>array('js/jbar/css/style.css')
    ),
  'jqn'=>array(
      'baseUrl'=>'/js/jqn',
      'js'=>array('jquery.notification.js'),
      'css'=>array('jquery.notification.css')
  ),
  'qt'=>array(
      'baseUrl'=>'/',
      'js'=>array('js/qt/jquery.betterTooltip.js'),
      'css'=>array('css/qt/style.css')
  ),
  'maphilight'=>array(
      'baseUrl'=>'/',
      'js'=>array('js/jquery.maphilight.js')
  ),
    'easing'=>array(
        'baseUrl'=>'/',
        'js'=>array('js/jquery.easing-1.3.pack.js')
    ),
    'mousewheel'=>array(
        'baseUrl'=>'/',
        'js'=>array('js/jquery.mousewheel-3.0.4.pack.js')
    ),
    'fancybox'=>array(
        'baseUrl'=>'/',
        'js'=>array('js/fancybox/jquery.fancybox-1.3.4.js'),
        'css'=>array('css/fancybox/jquery')
    ),
    'uni.form'=>array(
        'baseUrl'=>'/ext/uni-form',
        'js'=>array('js/uni-form.jquery.js'),
        'css'=>array('css/uni-form.css','css/default.uni-form.css')
    ),
    'hoverIntent'=>array(
      'baseUrl'=>'/js/superfish-1.4.8',
        'js'=>array('js/hoverIntent.js')
    ),
    'superfish'=>array(
        'baseUrl'=>'/js/superfish-1.4.8',
        'js'=>array('js/superfish.js'),
        'css'=>array('css/superfish.css'),
        'depends'=>array('jQuery','ui','hoverIntent')
    ),
    'onlineInformer'=>array(
        'baseUrl'=>'/js/models',
        'js'=>array('onlineInformer.js'),
        'depends'=>array('jQuery','ui')
    ),
    'wall'=>array(
        'baseUrl'=>'/js/models',
        'js'=>array('wall.js'),
        'depends'=>array('jQuery','ui')
    ),
    'noty'=>array(
        'baseUrl'=>'js/needim.notty',
        'js'=>array('js/jquery.noty.js'),
        'css'=>array('css/jquery.noty.css','css/noty_theme_default.css','css/noty_theme_twitter.css'),
        'depends'=>array('jQuery')
    ),
    'right.menu'=>array(
        'baseUrl'=>'/js/right.menu',
        'js'=>array('jquery.contextMenu.js','jquery.ui.position.js'),
        'css'=>array('jquery.contextMenu.css'),
        'depends'=>array('jQuery')
    ),
    'jquery.ms.filter'=>array(
        'baseUrl'=>'/js/jquery.ms',
        'js'=>array('jquery.multiselect.filter.js'),
        'css'=>array('jquery.multiselect.filter.css'),
        'depends'=>array('jQuery')
    ),
    'jquery.ms'=>array(
        'baseUrl'=>'/js/jquery.ms',
        'js'=>array('jquery.multiselect.min.js'),
        'css'=>array('jquery.multiselect.css'),
        'depends'=>array('jQuery','jquery.ms.filter')
    ),
    'adorn'=>array(
        'baseUrl'=>'/js/models',
        'js'=>array('adorn.js'),
        'depends'=>array('ui','jquery.ms')
    ),
    'frm'=>array(
        'baseUrl'=>'/js/models',
        'js'=>array('frm.js'),
        'depends'=>array('jquery.ui','adorn')
    ),
    'brw'=>array(
        'baseUrl'=>'/js/models',
        'js'=>array('brw.js'),
        'depends'=>array('jquery.ui','jqGrid','right.menu','adorn','frm','jquery.ms')
    ),
    'dinfo'=>array(
        'baseUrl'=>'/js/models',
        'js'=>array('dinfo.js'),
        'depends'=>array('jquery.ui','jqGrid','right.menu','adorn','frm','jquery.ms')
    ),
    'jDialog'=>array(
        'baseUrl'=>'/js/models',
        'js'=>array('jDialog.js'),
        'depends'=>array('jquery.ui','jqGrid','right.menu','adorn','frm','jquery.ms')
    ),
    'doc64'=>array(
        'baseUrl'=>'/js/models',
        'js'=>array('doc64.js'),
        'depends'=>array('jquery.ui','jqGrid','right.menu','adorn','frm','jquery.ms')
    ),
    'commoninfo'=>array(
        'baseUrl'=>'/js/models',
        'js'=>array('commoninfo.js'),
        'depends'=>array('jquery.ui','jqGrid','right.menu','adorn','frm','jquery.ms')
    )
);